language: swift
osx_image: xcode8.3
xcode_project: MAX.xcodeproj
xcode_scheme: MAXTests
xcode_sdk: iphonesimulator10.0

before_install:
  - pod repo add MAXPrivateCocoapods https://MAXCIUser:hDemzZsFc8KPboJchRdZhuNE@github.com/MAXAds/Specs

script:
  - make test
  - make check-version

# travis chokes on this because we have an empty .gitmodules file
git:
  submodules: false

notifications:
  slack: maxads:JKmg6ILKHgYKoQDXaGesbjIM
