language: swift
osx_image: xcode8.3
xcode_project: MAX.xcodeproj
xcode_scheme: MAXTests
xcode_sdk: iphonesimulator10.0

script:
  - set -o pipefail && xcodebuild -project MAX.xcodeproj -scheme MAX -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty

# travis chokes on this because we have an empty .gitmodules file
git:
  submodules: false

