language: objective-c
osx_image: xcode8.3

# travis chokes on this because we have an empty .gitmodules file
git:
  submodules: false

script: 
  - xcodebuild clean 
  - xcodebuild build -project MAX.xcodeproj -scheme MAX
  - xcodebuild test -project MAX.xcodeproj -scheme MAX -sdk iphonesimulator -destination "name=iPhone SE"

