language: objective-c
osx_image: xcode8.3

# travis chokes on this because we have an empty .gitmodules file
git:
  submodules: false

script: xcodebuild clean && xcodebuild build -project yourproject.xcodeproj -scheme yourscheme

