language: swift
osx_image: xcode9.2
xcode_project: MAX.xcodeproj
xcode_scheme: MAXTests
xcode_sdk: iphonesimulator10.0

sudo: required

before_script:
  - sudo gem install cocoapods --pre
  - pod repo update

script:
  - make test
  - make check-version

# travis chokes on this because we have an empty .gitmodules file
git:
  submodules: false

notifications:
  slack: maxads:JKmg6ILKHgYKoQDXaGesbjIM
