language: swift
osx_image: xcode9.1
xcode_project: MAX.xcodeproj
xcode_scheme: MAXTests
xcode_sdk: iphonesimulator10.0

before_install:
  - echo -e "machine github.com\n    login MAXCIUser\n    password hDemzZsFc8KPboJchRdZhuNE" >> ~/.netrc
  - pod repo add maxads https://MAXCIUser:hDemzZsFc8KPboJchRdZhuNE@github.com/MAXAds/Specs.git

script:
  - make test
  - make check-version

# travis chokes on this because we have an empty .gitmodules file
git:
  submodules: false

notifications:
  slack: maxads:JKmg6ILKHgYKoQDXaGesbjIM
