platform :ios, '9.0'

source 'https://github.com/MAXAds/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MAXiOSSampleAppObjC' do
  use_frameworks!

  pod 'Masonry', '~> 1.1'

#  pod 'MAX/Core', :git => 'git@github.com:MAXAds/max-ios-sdk-internal'
  pod 'MAX/Core', :path => "../.."
#  pod 'MAX/Facebook', :git => 'git@github.com:MAXAds/max-ios-sdk-internal'
  pod 'MAX/Facebook', :path => "../.."
#  pod 'MAX/Vungle', :git => 'git@github.com:MAXAds/max-ios-sdk-internal'
  pod 'MAX/Vungle', :path => "../.."


end
